### ISSUE TITLE
MiniTweaks crash

### ISSUE THREAD

**Issue by clmc99** [A5b84/convenient-mobgriefing#6]
Minecraft crashes on startup with only Convenient mobGriefing, Fabric API, MiniTweaks, and Carpet (MiniTweaks dependency) in the mods folder. Neither Convenient mobGriefing nor Carpet + MiniTweaks crashes by itself. Also created [an issue](https://github.com/manyrandomthings/minitweaks/issues/14) in the MiniTweaks GitHub. [latest.log](https://github.com/A5b84/convenient-mobgriefing/files/6660636/latest.log)

**Comment by A5b84** [comment]
Looks like those are the wrong logs (Convenient mobGriefing wasn't installed), I'll give it a try later but there's a (small?) chance the crash is because of [this line](https://github.com/A5b84/convenient-mobgriefing/blob/e665c13ba97961bdb71fa7393490b9d2647984f0/src/main/resources/convenient-mobgriefing.mixins.json#L24) not working anymore (maybe it never worked in the first place?)

**Comment by clmc99** [comment]
Sorry about that—[this should be the correct latest.log](https://github.com/A5b84/convenient-mobgriefing/files/6664416/latest.log). It looks like the problem is something with ender dragon griefing?

Update: It's ender dragon griefing. Minecraft boots normally when I remove all mention of ender dragon and recompile ([zip](https://github.com/A5b84/convenient-mobgriefing/files/6665093/convenient-mobgriefing-main.MODIFIED.zip)/[jar](https://drive.google.com/file/d/18or_i7FhZQC0KR_06C2mzOV5UTKa6gET/view?usp=sharing))

**Comment by A5b84** [comment]
Fixed in [v2.0.2](https://github.com/A5b84/convenient-mobgriefing/releases/tag/v2.0.2)
